<?php $buttons = $this->getButtons()?>
<?php $buttonsCount = count($buttons)?>
<?php $notLoginPage = $this->getCurrentPageRedirectUrl()?>
<?php
$cartPageAccordionState = $this->accordionStateOnCart();
/** @var \WeltPixel\SocialLogin\Helper\Data $slHelper */
$slHelper = $this->helper('WeltPixel\SocialLogin\Helper\Data');
$cspNonceProvider = $slHelper->getCspNonceProvider();
?>
<?php if(!empty($buttons) && !$this->isCustomerLoggedIn()):?>
    <div class="sociallogin-wrapper block-customer-login login-container">
        <div class="block sociallogin-block">
            <div class="sociallogin-block-title block-title">
                <strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Login With Social Profile'))?></strong>
            </div>
            <div class="sociallogin-padding">
                <?php foreach ($buttons as $type => $data):?>
                    <div class="sociallogin-box">
                        <a class="sociallogin-button button-<?= /* @noEscape */ $type?>"
                           rel="nofollow"
                           aria-label="<?= $block->escapeHtml(__('Login with %1', ucfirst($type)))?>"
                           href="javascript:void(0);"
                           data-href="<?= /* @noEscape */ $data['endpoint']?>"
                        >
                            <span class="sociallogin-icon sl-<?= /* @noEscape */ $type?>"></span>

                        </a>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    </div>
    <script<?php if ($cspNonceProvider): ?> nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->generateNonce()) ?>"<?php endif; ?>>
        if (window.socialloginButtons) {
            window.emailFormUrl = "<?= $block->escapeUrl($this->getEmailFormUrl())?>";
            window.twitterOauthUrl = "<?= $block->escapeUrl($this->getTwitterOauthUrl())?>";
            window.cartPageAccordionState = "<?= /* @noEscape */ $cartPageAccordionState?>";
            window.isCustomer = "<?= /* @noEscape */ $this->helper('WeltPixel\SocialLogin\Helper\Data')->loggedIn(); ?>";
            window.isSlCustomPopupUsed = "<?= /* @noEscape */ $this->helper('WeltPixel\SocialLogin\Helper\Data')->isPopupUsed(); ?>";
            require(['sociallogin'], function(){
                sl.socialLoginClick();
                sl.slWidgetInit('<?= /* @noEscape */ $buttonsCount?>');
                sl.sendEmailClick();
                sl.emailPopUp();
            });
        }
    </script>
<?php endif;?>
