<?php if($this->isRequired()):?>
<div class="reset-pass-msg"><?= $block->escapeHtml(__('You have logged in via one of the social media platforms and a password was generated for you. If you want to log in with your email, update your account settings and reset your password'))?> <a href="<?= $block->escapeUrl($this->getResetPasswordUrl())?>"><?= $block->escapeHtml(__('here'))?></a>.
</div>
<?php endif;?>
