<div class="block social-accounts">
    <div class="title"><strong><?= $block->escapeHtml(__('Linked Accounts')) ?></strong></div>
    <div class="content">
        <?php $socialAccounts = $this->getSocialAccounts()?>
        <?php if($socialAccounts):?>
            <ul class="sl-unlinks">
                <?php foreach($socialAccounts as $sAccounts): $type = ($sAccounts->getType() == 'fb') ? 'facebook' : $sAccounts->getType()?>
                    <li class="sl-link-line">
                        <a href="#" class="social-icons si-borderless si-<?= /* @noEscape */ $type?>" alt="<?= /* @noEscape */ $type?>" title="<?= /* @noEscape */ $type?>">
                            <i class="icon-<?= /* @noEscape */ $type?>"></i>
                            <i class="icon-<?= /* @noEscape */ $type?>"></i>
                        </a>

                        <span class="sl-link-name"><?= /* @noEscape */  $sAccounts->getFirstname() . ' ' .$sAccounts->getLastname()?></span>
                        <a class="sl-link-unlink social-icons si-borderless si-unlink" href="<?= /* @noEscape */  $this->getUnlinkUrl($sAccounts->getData('id'))?>" alt="<?= $block->escapeHtmlAttr(__("Unlink"))?>" title="<?=$block->escapeHtmlAttr(__("Unlink"))?>">
                            <i class="icon-unlink"></i>
                            <i class="icon-unlink"></i>
                        </a>

                    </li>
                <?php endforeach;?>
            </ul>
        <?php else :?>
            <div class="sl-noaccount"><?=$block->escapeHtml(__('No Linked Accounts'))?></div>
        <?php endif;?>

    </div>
</div>
