<div class="sl-copy-button">
    <button id="<?php  /* @noEscape */ echo $block->getId() ?>" class="copy-link" data-provider="<?php /* @noEscape */ echo $block->getDataProvider()?>">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
    <div id="copied_<?php  /* @noEscape */ echo $block->getDataProvider()?>"
         class="sl-admin-tooltip">
        <?= $block->escapeHtml(__('URL copied to clipboard.'))?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "WeltPixel_SocialLogin/js/copy_link":{
                "id": "<?= /* @noEscape */ $block->getId() ?>",
                "provider" : "<?= /* @noEscape */ $block->getDataProvider()?>"
            }
        }

    }
</script>
